stages:
  get_data:
    cmd: python get_data.py
    deps:
    - get_data.py
    outs:
    - data/flavors_of_cacao.csv
  process:
    cmd: python prepare_data.py
    deps:
    - prepare_data.py
    - data/flavors_of_cacao.csv
    outs:
    - data/data_processed.csv
  train:
    cmd: python train.py
    deps:
    - train.py
    - data/data_processed.csv
    metrics:
    - metrics.json:
        cache: false